### ISSUE TITLE
Keep getting an error while "Installing SharKF00D"

### ISSUE THREAD

**Issue by blackarcanis** [Rinnegatamante/VitaDB-Downloader#27] opened 2022-12-21 12:50 UTC
Hi!
Trying to install the VPK but at the step "Installing SharKF00D" it download and try to install the app without success.
Keep trying but the SharKF00D app generated 2 lines about a "module" and then crash. So I need to try again but it keeps doing the same issue.
Any idea?

**Comment by Rinnegatamante** [comment] 2022-12-22 20:34
Can you take a small video showing the error you get?

**Comment by Voyager-III** [comment] 2023-01-01 13:30
I had the same problem, when I launched VitaDB it was trying to download the libshacccg.suprx installer but I had to cancel it because it was stuck at 0% while downloading, when I tried to relaunch VitaDB it went straight to downloading SharKF00D and when it launched there was a quick flash of 3 lines of text and then it exited. So what I did was to install libshacccg.suprx manually (https://cimmerian.gitbook.io/vita-troubleshooting-guide/shader-compiler/extract-libshacccg.suprx) and now it is working perfect

**Comment by Rinnegatamante** [comment] 2023-01-01 13:46
> I had the same problem, when I launched VitaDB it was trying to download the libshacccg.suprx installer but I had to cancel it because it was stuck at 0% while downloading, when I tried to relaunch VitaDB it went straight to downloading SharKF00D and when it launched there was a quick flash of 3 lines of text and then it exited. So what I did was to install libshacccg.suprx manually (https://cimmerian.gitbook.io/vita-troubleshooting-guide/shader-compiler/extract-libshacccg.suprx) and now it is working perfect

On what firmware you were on? I start suspecting SharkF00D may have some issues with recent firmwares (the installation process had been tested on 3.60 and 3.65).

**Comment by Voyager-III** [comment] 2023-01-01 14:48
I bought a vita and received it two days ago it was on 3.70 so I modded it with final h-encore then used moduru to downgrade it to 3.60 and installed henkaku

**Comment by Rinnegatamante** [comment] 2023-01-01 15:01
So when you launched VitaDB Downloader for the first time, fw was 3.60, correct?

**Comment by Voyager-III** [comment] 2023-01-01 15:08
yes, but the first time I launched VitaDB it started downloading something but it was stuck at 0% it was probably my internet connection because I'm using my phone and the reception is crap where I am, but when I relaunched VitaDB It said downloading SharKF00D and that where the problem started, Was the first part of the download for the libshacccg.suprx files it must have skipped it because I canceled it the first time And did not restart from the begining when I relaunched VitaDB

**Comment by EpicLPer** [comment] 2023-01-06 19:25
Oh this sounds very similar to my #28 issue

**Comment by Rinnegatamante** [comment] 2023-01-15 16:07
Should be fixed by https://github.com/Rinnegatamante/VitaDB-Downloader/commit/176d6af9997bc611f82b5d3e775504a6d97de393 (At least the part caused by closing the app while it was downloading PSM runtime).

**Closed by Rinnegatamante** 2023-01-15 16:07 UTC
